name: Super_Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkou code
        uses: actions/checkout@v2
        
      - name: Runt Super-Linter
        uses: github/super-linter@v3.17.0
        env:
          DEFAULT_BRANCH: main
          GITHUB TOKEN: ${{ secrets.GITHUB_TOKEN }}
